language: cpp
before_script:
  - sudo apt-get install -y mpd curl libmpdclient-dev libgtest-dev
  
matrix:
  include:

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    
scritp: 
echo "PIES"
make
