language: cpp
before_script:
  - sudo apt-get install -y mpd curl libmpdclient-dev libgtest-dev
  
matrix:
  include:

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - chmod +x make_unit_test.sh
    - sudo ln /usr/bin/clang++-5.0 /usr/bin/clang++
    
script: "bash -c ./make_unit_test.sh"
