version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO && clang
          command: | 
                   apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
                   apt-get update && apt-get install -y gcc clang
      - run:
          name: Install CMAKE GIT and libs
          command: 'apt-get update && sudo apt-get install -y cmake git libmpd-dev curl libcurl4-openssl-dev libmpdclient-dev libgtest-dev google-mock'
      - run:
          name: google test init
          command: |
                   cd /usr/src/gtest
                   sudo cmake CMakeLists.txt
                   sudo make
                   sudo cp *.a /usr/lib
      - run:
          name: submodule init && update
          command: |
                   git submodule init
                   git submodule update --recursive --remote
      - run:
          name: ramdisk
          command: 'mkdir /mnt/ramdisk && touch /dev/tty0'
      - run:
          name: go to koko
          command: 'cd koko/'
      - run:
          name: du
          command: 'du iDom_server_OOP/test/config'
      - run:
          name: Creating Build Files
          command: 'cmake -Bkoko/ -Hkoko/'
      - run:
          name: ls
          command: 'ls'
      - run:
          name: Creating Binary Files
          command: 'make -C koko/'
      - run:
          name: ls
          command: 'ls koko/'
      - run:
          name: permision
          command: 'sudo chmod +x koko/koko'
      - run:
          name: runt
          command: './koko/koko'
          
      - run:
          name: Creating Build Files
          command: 'cmake -BiDom_server_OOP/test/iDom_TESTs-CMAKE/ -HiDom_server_OOP/test/iDom_TESTs-CMAKE/'
      - run:
          name: ls
          command: 'ls iDom_server_OOP/test/iDom_TESTs-CMAKE/'
      - run:
          name: Creating Binary Files
          command: 'make -j2 -C iDom_server_OOP/test/iDom_TESTs-CMAKE/'
      - run:
          name: ls
          command: 'ls iDom_server_OOP/test/iDom_TESTs-CMAKE/'
      - run:
          name: permision
          command: 'sudo chmod +x iDom_server_OOP/test/iDom_TESTs-CMAKE/iDom_TESTs-CMAKE'
      - run:
          name: runt
          command: './iDom_server_OOP/test/iDom_TESTs-CMAKE/iDom_TESTs-CMAKE'
      - run:
          name: show logs
          command: 'cat /mnt/ramdisk/iDom_log_BT.log'
          
