version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing clang
          command: 'apt-get update && apt-get install -y gcc clang'
      - run:
          name: Install CMAKE GIT
          command: 'apt-get update && sudo apt-get install -y cmake git'
      - run:
          name: ls
          command: 'ls'
      - run:
          name: clone 
          command: 'git clone https://github.com/cyniu88/malina.git'
      - run:
          name: go to koko
          command: 'cd malina/koko'
      - run:
          name: ls
          command: 'ls'
      - run:
          name: Creating Build Files
          command: 'cmake .'
      - run:
          name: Creating Binary Files
          command: 'make'
      - run:
          name: Point Unit Testing
          command: './koko'
