version: 2

aliases:
  - &docker_image ubuntu:bionic
  - &install_common |
      apt-get update -qq
      apt-get install -qq software-properties-common
      add-apt-repository -y ppa:ubuntu-toolchain-r/test
      apt-get update -qq
      apt-get install -qq autoconf automake gcc g++ libboost-dev libgtest-dev libopenmpi-dev libsparsehash-dev make pandoc gdb valgrind

jobs:

  build:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq clang-6.0
      - checkout
      - run: |
          ls /usr/bin
          clang-6.0 --version
